#!/usr/bin/env -S guile --no-auto-compile -s
!#
(use-modules (ice-9 getopt-long) (ice-9 rdelim) (development-caddy web))
(define options '((bind (single-char #\b) (value #t)) (port (single-char #\p) (value #t))
                  (caddy-admin-url (value #t)) (caddy-server (value #t)) (state-dir (value #t))
                  (help (single-char #\h))))
(define (usage)
  (display "Usage: development-caddy [OPTIONS]\n\nOptions:\n  -b, --bind ADDRESS\n  -p, --port PORT\n      --caddy-admin-url URL\n      --caddy-server NAME\n      --state-dir DIR\n  -h, --help\n"))
(define (fail message) (format (current-error-port) "development-caddy: ~a\n" message) (exit 2))
(define args (command-line))
(define parsed (catch #t (lambda () (getopt-long args options))
                      (lambda _ (fail "unknown option or missing option argument"))))
(when (pair? (option-ref parsed 'arguments '())) (fail "positional arguments are not allowed"))
(when (option-ref parsed 'help #f) (usage) (exit 0))
(define (value name default)
  (let ((x (option-ref parsed name default)))
    (if (and (string? x) (not (string-null? (string-trim-both x)))) (string-trim-both x)
        (fail (format #f "--~a must not be empty" name)))))
(define port-string (value 'port "11190"))
(define port (string->number port-string))
(unless (and port (integer? port) (<= 1 port 65535)) (fail "--port must be an integer from 1 to 65535"))
(define state (if (option-ref parsed 'state-dir #f) (value 'state-dir "")
                  (let ((base (or (getenv "XDG_STATE_HOME")
                                  (and (getenv "HOME") (string-append (getenv "HOME") "/.local/state")))))
                    (if base (string-append base "/development-caddy")
                        (fail "HOME or XDG_STATE_HOME must be set")))))
(run-server (value 'bind "127.0.0.1") port (value 'caddy-admin-url "http://127.0.0.1:2019")
            (value 'caddy-server "https") state (or (getenv "DEVELOPMENT_CADDY_STATIC") "."))
