[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write", "--prose-wrap", "always"]
includes = ["*.md"]

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]
excludes = ["tools/wave/*.rs", "tools/wave/src/*.rs"]

[formatter.wave-rust]
command = "rustfmt"
options = ["--edition", "2024"]
includes = ["tools/wave/*.rs", "tools/wave/src/*.rs"]
