{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib)
    mkEnableOption
    mkIf
    mkOption
    types
    ;
  cfg = config.programs.zen-browser;
  jsonFormat = pkgs.formats.json { };
  profileRoot =
    if pkgs.stdenv.isDarwin then
      "Library/Application Support/Zen"
    else
      lib.removePrefix "${config.home.homeDirectory}/" "${config.xdg.configHome}/zen";
  profilePath =
    if pkgs.stdenv.isDarwin then
      "${profileRoot}/Profiles/${cfg.profileName}"
    else
      "${profileRoot}/${cfg.profileName}";
  profilesIniPath = "${profileRoot}/profiles.ini";
  profileIniPath = if pkgs.stdenv.isDarwin then "Profiles/${cfg.profileName}" else cfg.profileName;
  settings =
    cfg.settings
    // lib.optionalAttrs (cfg.userChrome != null && builtins.readFile cfg.userChrome != "") {
      "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
    };
  serializePreference =
    value:
    builtins.toJSON (
      if builtins.isBool value || builtins.isInt value || builtins.isString value then
        value
      else
        builtins.toJSON value
    );
  userJs =
    "// Generated by Home Manager; edit modules/home/zen-browser/config/settings.nix.\n"
    + lib.concatStringsSep "\n" (
      lib.mapAttrsToList (
        name: value: "user_pref(${builtins.toJSON name}, ${serializePreference value});"
      ) settings
    )
    + "\n";
  profileIniAbsolutePath = "${config.home.homeDirectory}/${profilesIniPath}";
  managedFilePaths = [
    profileIniAbsolutePath
    "${config.home.homeDirectory}/${profilePath}/user.js"
  ]
  ++ lib.optional (
    cfg.userChrome != null
  ) "${config.home.homeDirectory}/${profilePath}/chrome/userChrome.css"
  ++ lib.optional (
    cfg.userContent != null
  ) "${config.home.homeDirectory}/${profilePath}/chrome/userContent.css";
  profilesIni = ''
    [General]
    StartWithLastProfile=1
    Version=2

    [Profile0]
    Name=${cfg.profileName}
    IsRelative=1
    Path=${profileIniPath}
    Default=1
    ${lib.optionalString (cfg.installId != null) ''

      [Install${cfg.installId}]
      Default=${profileIniPath}
      Locked=1
    ''}
  '';
in
{
  options.programs.zen-browser = {
    enable = mkEnableOption "Zen Browser profile management";

    package = mkOption {
      type = types.nullOr types.package;
      default = null;
      description = "Zen Browser package to install; null when Zen is installed outside Nix.";
    };

    profileName = mkOption {
      type = types.strMatching "^[A-Za-z0-9][A-Za-z0-9._-]*$";
      default = "wave";
      description = "Deterministic Zen profile name.";
    };

    installId = mkOption {
      type = types.nullOr (types.strMatching "^[0-9A-F]+$");
      default = null;
      description = "Optional Zen installation identifier used to select the managed profile.";
    };

    settings = mkOption {
      type = types.attrsOf jsonFormat.type;
      default = import ./config/settings.nix;
      description = "JSON-compatible Firefox/Zen preferences written to user.js.";
    };

    userChrome = mkOption {
      type = types.nullOr types.path;
      default = ./config/userChrome.css;
      description = "Optional source for the profile's chrome/userChrome.css.";
    };

    userContent = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Optional source for the profile's chrome/userContent.css.";
    };
  };

  config = mkIf cfg.enable {
    home = {
      packages = lib.optional (cfg.package != null) cfg.package;

      activation.zenBrowserProfiles = lib.hm.dag.entryBefore [ "linkGeneration" ] ''
        for managed_path in ${lib.concatMapStringsSep " " lib.escapeShellArg managedFilePaths}; do
          if [ -d "$managed_path" ]; then
            printf 'zen-browser: managed file target is a directory: %s\n' "$managed_path" >&2
            printf 'zen-browser: move it aside and retry Home Manager.\n' >&2
            exit 1
          fi
          if [ ! -e "$managed_path" ] && [ ! -L "$managed_path" ]; then
            continue
          fi

          managed_target=""
          if [ -L "$managed_path" ]; then
            managed_target=$(${pkgs.coreutils}/bin/readlink "$managed_path")
          fi
          case "$managed_target" in
            /nix/store/*)
              continue
              ;;
          esac

          managed_backup="''${managed_path}.home-manager-preexisting"
          if [ ! -e "$managed_backup" ] && [ ! -L "$managed_backup" ]; then
            ${pkgs.coreutils}/bin/cp -a "$managed_path" "$managed_backup"
          fi
        done
      '';

      file = {
        "${profilesIniPath}" = {
          text = profilesIni;
          force = true;
        };
        "${profilePath}/user.js" = {
          text = userJs;
          force = true;
        };
        "${profilePath}/chrome/userChrome.css" = mkIf (cfg.userChrome != null) {
          source = cfg.userChrome;
          force = true;
        };
        "${profilePath}/chrome/userContent.css" = mkIf (cfg.userContent != null) {
          source = cfg.userContent;
          force = true;
        };
      };
    };
  };
}
