(define-module (development-caddy caddy)
  #:use-module (web client) #:use-module (web response) #:use-module (web uri)
  #:use-module (json) #:use-module (development-caddy routes)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-11)
  #:use-module (system foreign)
  #:use-module (rnrs bytevectors)
  #:export (caddy-routes caddy-upsert caddy-delete))
(define (request-once base method path body)
  (let ((port #f))
    (dynamic-wind
      (lambda ()
        (set! port (open-socket-for-uri (string->uri (string-append base path))))
        ;; Guile 3.0 expects socket timeout values as (SECONDS . MICROSECONDS).
        (setsockopt port SOL_SOCKET SO_RCVTIMEO '(2 . 0))
        (setsockopt port SOL_SOCKET SO_SNDTIMEO '(2 . 0)))
      (lambda ()
        (let-values (((resp payload)
                      ;; Guile 3 returns an eager body unless streaming is requested.
                      (http-request (string->uri (string-append base path))
                                    #:method method #:body body #:port port
                                    #:headers (if body '((content-type application/json)) '()))))
          (values (response-code resp)
                  (cond ((string? payload) payload)
                        ((bytevector? payload) (utf8->string payload))
                        ((not payload) "")
                        (else "")))))
      (lambda ()
        (when (and port (not (port-closed? port)))
          (close-port port))))))
(define (request base method path body)
   (let* ((retry? (memq method '(GET PATCH DELETE)))
         (result (catch #t (lambda () (call-with-values (lambda () (request-once base method path body)) list))
                        (lambda _ '(599 "")))))
    (if (and retry? (= (car result) 599))
        (let ((retry-result (catch #t
                              (lambda () (call-with-values (lambda () (request-once base method path body)) list))
                              (lambda _ '(599 "")))))
          (when (= (car retry-result) 599)
            (format (current-error-port) "development-caddy: ~a ~a failed\n" method path))
          (values (car retry-result) (cadr retry-result)))
        (begin
          (when (= (car result) 599)
            (format (current-error-port) "development-caddy: ~a ~a failed\n" method path))
          (values (car result) (cadr result))))))
(define (id-path id) (uri-encode id))
(define (endpoint-id id)
  (string-append "/id/" (id-path id)))
(define (mutation-code? code) (<= 200 code 299))
(define (delete-code? code) (or (mutation-code? code) (= code 404)))
(define (legacy-ids id server)
  (let ((current (string-append id "_" server)))
    (filter (lambda (x) (not (string=? x current)))
            (delete-duplicates (list id (string-append id "_srv0")
                                     (string-append id "_srv1")) string=?))))
(define (delete-legacy base ids)
  (every (lambda (x)
           (let-values (((code _body) (request base 'DELETE (endpoint-id x) #f)))
             (delete-code? code)))
         ids))
(define (caddy-routes base server)
  (catch #t
    (lambda ()
      (let-values (((code body) (request base 'GET (string-append "/config/apps/http/servers/" server "/routes") #f)))
        (cond ((= code 404) '()) ((= code 200)
              (let ((x (json-string->scm body)))
                (cond ((vector? x) (vector->list x)) ((list? x) x) (else #f)))) (else #f))))
    (lambda _ #f)))
(define (caddy-upsert base server id host upstream)
  (let* ((current (string-append id "_" server))
         (legacy (legacy-ids id server))
         (json (route-json current host upstream)))
     (let-values (((patch-code _patch-body) (request base 'PATCH (endpoint-id current) json)))
       (cond
        ((mutation-code? patch-code) (and (delete-legacy base legacy) #t))
        ((= patch-code 404)
        (let-values (((post-code _post-body)
                      (request base 'POST
                               (string-append "/config/apps/http/servers/" server "/routes")
                               json)))
          (and (mutation-code? post-code) (delete-legacy base legacy))))
       (else #f)))))
(define (caddy-delete base server id)
  (let ((ids (delete-duplicates (list (string-append id "_" server) id
                                      (string-append id "_srv0") (string-append id "_srv1")) string=?)))
   (every (lambda (x) (let-values (((code _body) (request base 'DELETE (endpoint-id x) #f))) (delete-code? code))) ids)))
