(define-module (development-caddy deadlines)
  #:use-module (json)
  #:use-module (ice-9 ftw)
  #:use-module (ice-9 regex)
  #:use-module (ice-9 rdelim)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-19)
  #:use-module (rnrs io ports)
  #:export (deadline-valid? deadline-error deadline-load deadline-save deadline-reset
            deadline-days deadline-grid deadline-expired?))

;; Days since an arbitrary Gregorian epoch.  This deliberately does not use
;; time_t: deadlines are calendar dates, and must not change at DST boundaries.
(define (civil-day y m d)
  (let* ((y (- y (if (<= m 2) 1 0)))
         (era (floor-quotient y 400)) (yoe (- y (* era 400)))
         (mp (+ m (if (> m 2) -3 9)))
         (doy (+ (floor-quotient (+ (* 153 mp) 2) 5) (- d 1)))
         (doe (+ (* yoe 365) (floor-quotient yoe 4) (- (floor-quotient yoe 100)) doy)))
    (+ (* era 146097) doe)))

(define (iso-date x)
  (and (string? x)
       (let ((m (string-match "^([0-9]{4})-([0-9]{2})-([0-9]{2})$" x)))
         (and m (let* ((y (string->number (match:substring m 1)))
                       (mo (string->number (match:substring m 2)))
                       (da (string->number (match:substring m 3)))
                       (leap (or (= (modulo y 400) 0) (and (= (modulo y 4) 0) (not (= (modulo y 100) 0)))))
                       (maxd (if (<= 1 mo 12) (list-ref '(31 28 31 30 31 30 31 31 30 31 30 31) (- mo 1)) 0)))
                  (and (<= 1 mo 12) (<= 1 da (+ maxd (if (and (= mo 2) leap) 1 0)))
                       (catch #t
                  (lambda ()
                    (let ((d (string->date x "~Y-~m-~d")))
                      (and (string=? (date->string d "~Y-~m-~d") x) d)))
                  (lambda _ #f))))))))
(define (day x)
  (let ((d (iso-date x))) (civil-day (date-year d) (date-month d) (date-day d))))
(define (valid-label? x)
  (and (string? x) (let ((s (string-trim-both x)))
                    (and (not (string-null? s)) (<= (string-length s) 200)))))
(define (deadline-valid? d)
  (and (list? d) (= 4 (length d))
       (equal? (assoc-ref d "version") 1)
       (valid-label? (assoc-ref d "label"))
       (iso-date (assoc-ref d "start_date")) (iso-date (assoc-ref d "end_date"))
       (<= (day (assoc-ref d "start_date")) (day (assoc-ref d "end_date")))))
(define (deadline-error d)
  (cond ((not (valid-label? (assoc-ref d "label"))) "can't be blank")
        ((or (not (iso-date (assoc-ref d "start_date")))
             (not (iso-date (assoc-ref d "end_date")))) "is invalid")
        ((> (day (assoc-ref d "start_date")) (day (assoc-ref d "end_date")))
         "must be on or after start date")
        (else "is invalid")))
(define (deadline-days d today)
  (let* ((a (day (assoc-ref d "start_date"))) (b (day (assoc-ref d "end_date")))
         (t (day today)))
    (list (+ 1 (- b a)) (max 0 (+ 1 (- t a))) (max 0 (- b t)))))
(define (deadline-grid d today)
  (let* ((n (car (deadline-days d today))) (a (day (assoc-ref d "start_date"))) (t (day today)))
    (let loop ((i 0) (out '()))
      (if (>= i n) (reverse out)
          (let ((week (map (lambda (j) (let ((x (+ a j)))
                                          (cond ((< x t) 'elapsed) ((= x t) 'today) (else 'future))))
                            (iota (min 8 (- n i)) i))))
            (loop (+ i (length week)) (cons week out)))))))
(define (deadline-expired? d today) (> (day today) (day (assoc-ref d "end_date"))))

(define (mkdir-p/secure p)
  (unless (or (string-null? p) (string=? p ".") (file-exists? p))
    (mkdir-p/secure (dirname p))
    (mkdir p)
    (chmod p #o700)))
(define (deadline-load path)
  (if (not (file-exists? path)) 'missing
      (catch #t (lambda ()
                  (let ((d (json-string->scm (call-with-input-file path get-string-all))))
                    (if (deadline-valid? d) d 'corrupt)))
            (lambda _ 'corrupt))))
(define (deadline-save path d)
  (let ((clean (catch #t
                 (lambda ()
                   (and (list? d)
                        (every (lambda (p) (and (pair? p) (string? (car p)))) d)
                        (map (lambda (p) (if (and (string=? (car p) "label") (string? (cdr p)))
                                             (cons (car p) (string-trim-both (cdr p))) p)) d)))
                 (lambda _ #f))))
    (if (not (deadline-valid? clean)) (values #f (deadline-error (or clean '())))
        (let ((tmp #f))
          (catch #t
            (lambda ()
              (let ((dir (dirname path))) (mkdir-p/secure dir)
                (let* ((tv (get-internal-real-time))
                       (name (string-append dir "/.deadline." (number->string (getpid)) "." (number->string tv) ".tmp")))
                  (set! tmp (cons name (open-file name "w"))))
                (chmod (car tmp) #o600)
                (display (scm->json-string clean) (cdr tmp)) (newline (cdr tmp)) (force-output (cdr tmp)) (close-port (cdr tmp))
                (rename-file (car tmp) path) (set! tmp #f) (values #t #f)))
            (lambda _ (when (and tmp (not (port-closed? (cdr tmp)))) (close-port (cdr tmp)))
                    (when (and tmp (file-exists? (car tmp))) (delete-file (car tmp)))
                    (values #f "could not save deadline")))))))
(define (deadline-reset path) (catch #t (lambda () (when (file-exists? path) (delete-file path)) #t) (lambda _ #f)))
