(define-module (development-caddy routes)
  #:use-module (json) #:use-module (ice-9 regex) #:use-module (srfi srfi-1)
  #:export (parse-route-payload group-routes route-json))
(define (printable? s) (and (string? s) (not (string-null? s))
                            (every (lambda (c) (and (char>=? c #\space) (char<=? c #\~))) (string->list s))))
(define (bounded? x n) (and (printable? x) (<= (string-length x) n)))
(define (safe-id? x) (and (bounded? x 128) (string-match "^[A-Za-z0-9._-]+$" x)))
(define (valid-host? x)
  (and (bounded? x 253) (string-suffix? ".localhost" x)
       (let ((ls (string-split x #\.)))
         (and (>= (length ls) 2) (every (lambda (l) (and (<= 1 (string-length l) 63)
             (string-match "^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$" l))) ls)
               (not (string=? (car (reverse ls)) ""))))))
(define (valid-decimal-range? s low high)
  (and (string-match "^[0-9]+$" s)
       (let ((n (string->number s)))
         (and n (integer? n) (<= low n high)))))
(define (valid-port? s) (valid-decimal-range? s 1 65535))
(define (valid-loopback-ipv4? address)
  (let ((octets (string-split address #\.)))
    (and (= 4 (length octets))
         (every (lambda (octet) (valid-decimal-range? octet 0 255)) octets)
         (= 127 (string->number (car octets))))))
(define (loopback? x)
  (and (bounded? x 128)
       (let ((colon (string-rindex x #\:)))
         (and colon
              (valid-port? (substring x (+ colon 1)))
              (let ((address (substring x 0 colon)))
                (or (string=? address "localhost")
                    (string=? address "[::1]")
                    (valid-loopback-ipv4? address)))))))
(define (parse-route-payload body)
  (catch #t (lambda ()
              (let ((x (json-string->scm body)))
                (and (list? x) (= 3 (length x))
                     (every (lambda (p) (and (pair? p) (member (car p) '("id" "hostname" "upstream")))) x)
                     (= 3 (length (delete-duplicates (map car x))))
                     (let ((id (assoc-ref x "id")) (h (assoc-ref x "hostname")) (u (assoc-ref x "upstream")))
                       (and (safe-id? id) (valid-host? h) (loopback? u)
                            (list (cons "id" id) (cons "hostname" h) (cons "upstream" u)))))))
        (lambda _ #f)))
(define (route-json id hostname upstream)
  (scm->json-string (list (cons "@id" id)
                          (cons "match" (vector (list (cons "host" (vector hostname)))))
                          (cons "handle" (vector (list (cons "handler" "reverse_proxy")
                                                        (cons "upstreams" (vector (list (cons "dial" upstream))))))))))
(define (route-info r)
  (catch #t (lambda ()
    (and (list? r) (string? (assoc-ref r "@id"))
         (let* ((m (or (and (vector? (assoc-ref r "match")) (vector->list (assoc-ref r "match"))) (assoc-ref r "match")))
                (h (and (list? m) (pair? m) (assoc-ref (car m) "host")))
                (host (and (vector? h) (= 1 (vector-length h)) (vector-ref h 0))) (parts (and host (string-split host #\.)))
                (handles (or (and (vector? (assoc-ref r "handle")) (vector->list (assoc-ref r "handle"))) (assoc-ref r "handle"))) (handler (and (list? handles) (pair? handles) (car handles)))
                (ups (and (list? handler) (string=? (or (assoc-ref handler "handler") "") "reverse_proxy")
                          (assoc-ref handler "upstreams")))
                (ups* (or (and (vector? ups) (vector->list ups)) ups))
                (dial (and (list? ups*) (= 1 (length ups*)) (assoc-ref (car ups*) "dial"))))
           (and (valid-host? host) (>= (length parts) 3) (string? dial)
                (cons (cons "project" (string-join (take (cdr parts) (- (length parts) 2)) "."))
                      (list (cons "branch" (car parts)) (cons "hostname" host) (cons "id" (assoc-ref r "@id")) (cons "upstream" dial)))))))
    (lambda _ #f)))
(define (group-routes routes)
  (let* ((xs (delete-duplicates (filter-map route-info (if (list? routes) routes '()))
                                (lambda (a b) (string=? (assoc-ref a "hostname") (assoc-ref b "hostname")))))
         (ps (delete-duplicates (map (lambda (x) (assoc-ref x "project")) xs) string=?))
         (cmp (lambda (a b) (string<? a b))))
    (map (lambda (p) (cons p (sort (filter (lambda (x) (string=? p (assoc-ref x "project"))) xs)
                                   (lambda (a b) (cmp (assoc-ref a "branch") (assoc-ref b "branch"))))))
         (sort ps cmp))))
