(define-module (development-caddy web)
  #:use-module (web server) #:use-module (web request) #:use-module (web response)
  #:use-module (web http) #:use-module (web uri) #:use-module (sxml simple)
  #:use-module (ice-9 rdelim) #:use-module (ice-9 regex)
  #:use-module (rnrs bytevectors) #:use-module (rnrs io ports)
  #:use-module (srfi srfi-1) #:use-module (srfi srfi-19) #:use-module (json)
  #:use-module (srfi srfi-11)
  #:use-module (development-caddy deadlines) #:use-module (development-caddy routes)
  #:use-module (development-caddy caddy)
  #:use-module (development-caddy bounded-http)
  #:export (run-server))

(define themes '("kanagawa" "kanagawa-lotus"))
(define mutation-limit 16384)
(define (today) (date->string (current-date) "~Y-~m-~d"))
(define (v a k) (or (assoc-ref a k) ""))
(define (xml x) (call-with-output-string (lambda (p) (sxml->xml x p))))

(define (decode x)
  (uri-decode (string-map (lambda (c) (if (char=? c #\+) #\space c)) x)))
(define (form-body s)
  (if (or (not s) (string-null? s)) '()
      (map (lambda (x) (let ((p (string-index x #\=)))
                         (cons (decode (if p (substring x 0 p) x))
                               (decode (if p (substring x (+ p 1)) "")))))
           (string-split s #\&))))

;; Bodies are deliberately bounded before parsing.  Ports are always closed.
(define (read-body body)
  (define (decode-bounded bv)
    (if (> (bytevector-length bv) mutation-limit) 'oversized
        (catch #t (lambda () (utf8->string bv)) (lambda _ 'invalid))))
  (cond ((not body) "") ((oversized-body? body) 'oversized)
        ((string? body) (decode-bounded (string->utf8 body)))
        ((bytevector? body) (decode-bounded body))
        ((port? body) (let ((bv (get-bytevector-n body (+ mutation-limit 1))))
                        (close-port body) (decode-bounded bv)))
        (else 'invalid)))

(define (h name value) (cons name (parse-header name value)))
(define (base-headers type cache)
  (list (h 'content-type type) (h 'cache-control cache)
        (h 'x-content-type-options "nosniff") (h 'x-frame-options "DENY")
        (h 'referrer-policy "same-origin")
        (h 'content-security-policy
           "default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self'; connect-src 'self'; form-action 'self' https://duckduckgo.com")))
(define* (reply code type body #:optional (extra '()))
  (values (build-response #:code code #:headers (append extra (base-headers type "no-store"))) body))
(define* (redirect location #:optional (extra '()))
  (values (build-response #:code 303 #:headers (append (list (h 'location location)) extra
                                                        (base-headers "text/plain; charset=utf-8" "no-store"))) ""))
(define (field name value)
  `(input (@ (id ,(string-append "deadline-" name)) (type "text") (name ,name)
             (value ,(or value "")) (placeholder "Label (e.g., Sprint 1)"))))

(define (valid-deadline d)
  (and (list? d) (deadline-valid? d) d))

;; Increment civil dates, rather than seconds, so DST cannot affect titles.
(define (grid-date start offset)
  (let* ((m (string-match "^([0-9]{4})-([0-9]{2})-([0-9]{2})$" start))
         (y (string->number (match:substring m 1)))
         (mo (string->number (match:substring m 2)))
         (da (+ (string->number (match:substring m 3)) offset)))
    (let loop ((year y) (month mo) (day da))
      (let* ((leap (or (= (modulo year 400) 0)
                       (and (= (modulo year 4) 0) (not (= (modulo year 100) 0)))))
             (lengths '(31 28 31 30 31 30 31 31 30 31 30 31))
             (last (+ (list-ref lengths (- month 1)) (if (and leap (= month 2)) 1 0))))
        (if (<= day last)
            (format #f "~4,'0d-~2,'0d-~2,'0d" year month day)
            (loop (if (= month 12) (+ year 1) year)
                  (if (= month 12) 1 (+ month 1)) (- day last)))))))

;; Keep the form as a separate constructor so error values are never discarded.
(define (deadline-form* d error edit? notice)
  `(div (@ (class "deadline"))
     ,(if notice `(p (@ (class "error") (role "alert")) ,notice) "")
      ,(if error `(p (@ (class "form-error") (role "alert")) ,error) "")
      (form (@ (action "/deadline") (method "post") (class "deadline-form") (data-fragment "deadline"))
        (label (@ (class "visually-hidden") (for "deadline-label")) "Label")
        ,(field "label" (and d (v d "label")))
        (label (@ (class "visually-hidden") (for "deadline-end_date")) "End date")
        (input (@ (id "deadline-end_date") (type "date") (name "end_date")
                  (value ,(or (and d (v d "end_date")) ""))))
        (button (@ (type "submit")) "Set Deadline"))
      ,(if (and notice (string=? notice "Saved deadline data is corrupt. Create a new deadline or reset it."))
           `(form (@ (action "/deadline/reset") (method "post") (class "deadline-reset-form") (data-fragment "deadline"))
              (button (@ (type "submit") (class "button-reset")) "Reset deadline")) "")))

(define* (deadline-section d state #:optional (error #f) (edit? #f) (notice #f))
  (if (or (eq? state 'missing) (eq? state 'corrupt) edit? (not (valid-deadline d)))
      (deadline-form* (and (list? d) d) error edit? (or notice (and (eq? state 'corrupt) "Saved deadline data is corrupt. Create a new deadline or reset it.")))
         (let* ((ds (deadline-days d (today))) (grid (deadline-grid d (today)))
                (start (v d "start_date")))
        `(div (@ (class "deadline"))
           (div (@ (class "deadline-header"))
              (form (@ (action "/deadline/edit") (method "get") (class "deadline-edit-form"))
                (button (@ (class "deadline-label button-reset") (type "submit") (title "Click to edit") (data-fragment "deadline-edit")) ,(v d "label")))
             (span (@ (class "deadline-stats")) ,(format #f "~a/~a days (~a remaining)" (cadr ds) (car ds) (caddr ds))))
            (div (@ (class "deadline-grid"))
              ,@(let week-loop ((weeks grid) (offset 0))
                  (if (null? weeks) '()
                      (let ((week (car weeks)))
                        (let ((days (map (lambda (kind i)
                                            `(div (@ (class ,(string-append "deadline-day " (symbol->string kind)))
                                                      (title ,(grid-date start (+ offset i)))) "") )
                                         week (iota (length week)))))
                          (cons (cons 'div (cons '(@ (class "deadline-week")) days))
                                 (append (if (null? (cdr weeks)) '() (list `(div (@ (class "deadline-week-gap")) "")))
                                          (week-loop (cdr weeks) (+ offset (length week)))))))))))
  )))

(define (countdown d)
  (if (and (list? d) (not (deadline-expired? d (today))))
      `(div (@ (id "countdown") (class "countdown") (data-end-date ,(v d "end_date"))) "")
       (if (list? d) `(div (@ (id "countdown") (class "countdown expired")) "00:00:00:00")
            `(div (@ (id "countdown") (class "countdown")) ""))))

(define* (deadline-ui display state #:optional (error #f) (edit? #f)
                      (submitted #f) (reset-error #f))
  `(div (@ (id "deadline-ui"))
     ,(countdown (valid-deadline display))
     (div (@ (class "countdown-label"))
       ,(if (and (valid-deadline display)
                 (deadline-expired? display (today)))
            (v display "label") ""))
     (div (@ (class "countdown-reset"))
       ,(if reset-error `(p (@ (class "error") (role "alert"))
                            "could not reset deadline") "")
       ,(if (and (valid-deadline display)
                 (deadline-expired? display (today)))
            `(form (@ (action "/deadline/reset") (method "post")
                      (class "deadline-reset-form") (data-fragment "deadline"))
               (button (@ (type "submit") (class "button-reset"))
                       "set a new deadline")) ""))
     (form (@ (action "https://duckduckgo.com/") (method "get")
              (class "search-form"))
       (label (@ (class "visually-hidden") (for "search")) "Search")
       (input (@ (id "search") (type "text") (name "q")
                 (class "search-input") (placeholder "Search DuckDuckGo...")
                 (autocomplete "off") (autofocus "autofocus"))))
     (section (@ (id "deadline-section"))
       ,(deadline-section (or submitted display) state error edit?))))

(define (routes-fragment grouped error)
   (cons 'section (cons '(@ (id "routes-section"))
      (cond (error (list `(div (@ (class "error") (role "alert")) "Failed to fetch routes: Caddy admin API unavailable")))
           ((null? grouped) (list `(div (@ (class "empty")) (p "No worktree environments running.") (p (@ (class "empty-note")) "Start a worktree with worktrunk to see it here."))))
          (else (map (lambda (g) `(div (@ (class "project")) (div (@ (class "project-header")) ,(car g))
            (ul (@ (class "branch-list")) ,@(map (lambda (r) `(li (@ (class "branch-item"))
              (a (@ (href ,(string-append "https://" (v r "hostname"))) (target "_blank") (rel "noopener noreferrer")
                  (title ,(v r "upstream")))
                (svg (@ (class "branch-icon") (viewBox "0 0 24 24") (stroke-width "1.5") (fill "none") (xmlns "http://www.w3.org/2000/svg"))
                  ,@(map (lambda (path) `(path (@ (d ,path) (stroke "currentColor") (stroke-linecap "round") (stroke-linejoin "round")))) branch-paths))
                ,(v r "branch")))) (cdr g))))) grouped))))))

(define branch-paths '("M18 21C19.1046 21 20 20.1046 20 19C20 17.8954 19.1046 17 18 17C16.8954 17 16 17.8954 16 19C16 20.1046 16.8954 21 18 21Z"
  "M6 7C7.10457 7 8 6.10457 8 5C8 3.89543 7.10457 3 6 3C4.89543 3 4 3.89543 4 5C4 6.10457 4.89543 7 6 7Z"
  "M6 21C7.10457 21 8 20.1046 8 19C8 17.8954 7.10457 17 6 17C4.89543 17 4 17.8954 4 19C4 20.1046 4.89543 21 6 21Z"
  "M6 7V17" "M18 17V7C18 7 18 5 16 5H13" "M15.0005 7.50012L12.5005 5.00012L15.0005 2.50012"))
(define* (page d state theme grouped error #:optional (deadline-error #f) (edit? #f) (form-d #f) (reset-error #f))
  (let ((next (if (string=? theme "kanagawa") "kanagawa-lotus" "kanagawa")))
    `(html (@ (lang "en") (data-theme ,theme)) (head (meta (@ (charset "utf-8")))
      (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
      (link (@ (rel "icon") (type "image/png") (href "/images/favicon.png"))) (title "Development Caddy")
       (link (@ (rel "stylesheet") (href "/assets/css/app.css"))) (script (@ (defer "defer") (src "/assets/js/app.js")) ""))
      (body (div (@ (class "container")) (header (img (@ (src "/images/logo.png") (alt "Caddy") (class "logo"))))
             ,(deadline-ui d state deadline-error edit? form-d reset-error)
             (main ,(routes-fragment grouped error)))
      (footer (@ (class "theme-toggle-footer")) (form (@ (action "/theme") (method "post"))
        (input (@ (type "hidden") (name "theme") (value ,next))) (button (@ (type "submit") (class "theme-toggle") (aria-label ,(if (string=? theme "kanagawa") "Switch to light theme" "Switch to dark theme")))
             ,(if (string=? theme "kanagawa")
                  `(svg (@ (class "theme-icon") (viewBox "0 0 24 24") (fill "none") (stroke "currentColor") (stroke-width "1.5")) (circle (@ (cx "12") (cy "12") (r "5"))) (path (@ (d "M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"))))
                  `(svg (@ (class "theme-icon") (viewBox "0 0 24 24") (fill "none") (stroke "currentColor") (stroke-width "1.5")) (path (@ (d "M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79Z"))))))))))))

(define (header-value req name)
  (let ((x (assq-ref (request-headers req) name)))
     (cond ((string? x) x) ((pair? x) (or (and (string? (cdr x)) (cdr x)) (format #f "~a" x))) (else #f))))
(define (header-raw req name) (assq-ref (request-headers req) name))
(define (effective-port scheme port)
  (let ((s (if (symbol? scheme) (symbol->string scheme) (or scheme "http"))))
    (or (and port (if (string? port) (string->number port) port))
        (if (string-ci=? s "https") 443 80))))
(define (same-origin-uri? host-header uri)
  (and (pair? host-header) (uri? uri)
       (string-ci=? (car host-header) (or (uri-host uri) ""))
       (= (effective-port (or (uri-scheme uri) "http") (cdr host-header))
          (effective-port (or (uri-scheme uri) "http") (uri-port uri)))))
(define (parse-uri x)
  (cond ((uri? x) x) ((string? x) (catch #t (lambda () (string->uri x)) (lambda _ #f))) (else #f)))
(define (cookie-theme req)
  (let ((x (header-value req 'cookie)))
    (and x (let ((m (string-match "(^|;[ ]*)theme=([^;]+)" x))) (and m (match:substring m 2))))))
(define (same-origin? req)
  (let* ((host (header-raw req 'host)) (origin (header-raw req 'origin))
         (referer (header-raw req 'referer))
         (forwarded (header-value req 'x-forwarded-proto))
         (scheme (and (or (not forwarded) (member (string-downcase forwarded) '("http" "https")))
                      (if forwarded (string-downcase forwarded) "http")))
         (matches? (lambda (raw)
                     (let ((u (parse-uri raw)))
                        (and (same-origin-uri? host u) (uri-scheme u)
                             (string-ci=? scheme (symbol->string (uri-scheme u))))))))
    (and scheme (or origin referer) (or (not origin) (matches? origin))
         (or (not referer) (matches? referer)))))
(define (safe-location req)
  (let ((r (parse-uri (header-raw req 'referer))) (h (header-raw req 'host)))
    (if (and (same-origin? req) (same-origin-uri? h r)) (uri->string r) "/")))

(define static-paths '("/assets/css/app.css" "/assets/js/app.js" "/images/logo.png" "/images/favicon.png" "/favicon.ico"))
(define font-paths '("/fonts/overpass-regular.woff2" "/fonts/overpass-600.woff2" "/fonts/overpass-700.woff2" "/fonts/overpass-mono-regular.woff2" "/fonts/overpass-mono-700.woff2"))
(define (static-response root path)
  (if (not (member path (append static-paths font-paths))) (reply 404 "text/plain" "not found\n")
      (let ((file (string-append root path)))
        (if (not (file-exists? file)) (reply 404 "text/plain" "not found\n")
            (let ((type (cond ((string-suffix? ".css" path) "text/css; charset=utf-8") ((string-suffix? ".js" path) "text/javascript; charset=utf-8") ((string-suffix? ".woff2" path) "font/woff2") ((string-suffix? ".ico" path) "image/x-icon") (else "image/png"))))
              (values (build-response #:code 200 #:headers (base-headers type "public, max-age=31536000, immutable"))
                      (if (or (string-suffix? ".css" path) (string-suffix? ".js" path)) (call-with-input-file file get-string-all) (call-with-input-file file get-bytevector-all))))))))

(define (run-server bind port admin server state-dir static-dir)
  (let ((state (string-append state-dir "/deadline.json")))
    (define (fragment? req)
      (string=? (or (header-value req 'x-development-caddy-fragment) "") "deadline"))
    (define (theme req)
      (let ((candidate (cookie-theme req)))
        (if (member candidate themes) candidate "kanagawa")))
     (define* (html-page req d deadline-state routes-error #:optional (deadline-error #f) (edit? #f) (form-d #f) (reset-error #f))
      (let ((routes (caddy-routes admin server)))
        (string-append "<!doctype html>"
                       (xml (page d deadline-state (theme req)
                                  (if routes (group-routes routes) '())
                                     (or routes-error (not routes)) deadline-error edit? form-d reset-error)))))
     (define* (render-deadline req d deadline-state error edit? notice #:optional (active #f))
      (cond
       ((fragment? req)
        (reply (if error 422 200) "text/html; charset=utf-8"
                (xml (deadline-ui (or (valid-deadline active) (valid-deadline d)) deadline-state error edit? d))))
       (error
        (reply 422 "text/html; charset=utf-8"
                 (html-page req (or (valid-deadline active) (valid-deadline deadline-state)) deadline-state #f error edit? d)))
       (edit?
        (reply 200 "text/html; charset=utf-8"
               (html-page req d deadline-state #f #f #t)))
       (else (redirect "/"))))
    (define (main-response req)
      (let ((d (deadline-load state)))
        (reply 200 "text/html; charset=utf-8"
               (html-page req (and (list? d) d) d #f))))
    (define (routes-response)
      (let ((routes (caddy-routes admin server)))
        (reply 200 "text/html; charset=utf-8"
               (xml (routes-fragment (if routes (group-routes routes) '())
                                     (not routes))))))
    (define (save-deadline req body)
      (if (not (same-origin? req))
          (reply 403 "text/plain" "forbidden\n")
           (if (memq body '(oversized invalid))
               (reply (if (eq? body 'oversized) 413 400) "text/plain" (if (eq? body 'oversized) "body too large\n" "invalid body\n"))
              (let* ((fields (form-body body))
                     (old (deadline-load state))
                     (d (list (cons "version" 1)
                              (cons "start_date" (if (list? old) (v old "start_date") (today)))
                              (cons "label" (or (assoc-ref fields "label") ""))
                              (cons "end_date" (or (assoc-ref fields "end_date") "")))))
                (let-values (((ok error) (deadline-save state d)))
                  (if ok
                      (if (fragment? req)
                          (render-deadline req d d #f #f #f)
                          (redirect "/"))
                       (render-deadline req d old error #t #f old)))))))
     (define (reset-deadline req body)
       (if (not (same-origin? req))
           (reply 403 "text/plain" "forbidden\n")
            (if (memq body '(oversized invalid))
                (reply (if (eq? body 'oversized) 413 400) "text/plain" (if (eq? body 'oversized) "body too large\n" "invalid body\n"))
                (let ((ok (deadline-reset state)))
                  (if ok
                      (render-deadline req #f 'missing #f #f #f)
                      (let ((current (deadline-load state)))
                        (if (fragment? req)
                            (reply 500 "text/html; charset=utf-8"
                                   (xml (deadline-ui current current #f #f #f #t)))
                            (reply 500 "text/html; charset=utf-8"
                                    (html-page req current current #f #f #f #f #t)))))))))
    (define (save-theme req body)
      (if (not (same-origin? req))
          (reply 403 "text/plain" "forbidden\n")
           (if (memq body '(oversized invalid))
               (reply (if (eq? body 'oversized) 413 400) "text/plain" (if (eq? body 'oversized) "body too large\n" "invalid body\n"))
              (let ((selected (assoc-ref (form-body body) "theme")))
                (if (member selected themes)
                    (redirect (safe-location req)
                              (list (h 'set-cookie
                                       (string-append "theme=" selected
                                                      "; Max-Age=31536000; Path=/; SameSite=Lax"))))
                    (reply 400 "text/plain" "invalid theme\n"))))))
    (define (api-upsert body)
       (if (memq body '(oversized invalid))
           (reply (if (eq? body 'oversized) 413 400) "application/json; charset=utf-8"
                  (if (eq? body 'oversized) "{\"error\":\"body too large\"}" "{\"error\":\"invalid body\"}"))
          (let ((route (parse-route-payload body)))
            (if (not route)
                (reply 400 "application/json; charset=utf-8" "{\"error\":\"invalid route\"}")
                (if (caddy-upsert admin server (v route "id")
                                  (v route "hostname") (v route "upstream"))
                    (reply 200 "application/json; charset=utf-8" "{\"status\":\"ok\"}")
                    (reply 502 "application/json; charset=utf-8" "{\"error\":\"caddy unavailable\"}"))))))
    (define (route-id path)
      (and (string-prefix? "/api/routes/" path)
           (let ((raw (substring path 12)))
             (and (not (string-null? raw)) (not (string-index raw #\/)) raw))))
     (define (api-delete path body)
       (cond
        ((eq? body 'oversized)
         (reply 413 "application/json; charset=utf-8" "{\"error\":\"body too large\"}"))
        ((eq? body 'invalid)
         (reply 400 "application/json; charset=utf-8" "{\"error\":\"invalid body\"}"))
        (else
         (let* ((raw (route-id path))
                (id (and raw (string-match "^[A-Za-z0-9._~%-]+$" raw)
                         (catch #t (lambda () (uri-decode raw)) (lambda _ #f)))))
           (if (and id (string-match "^[A-Za-z0-9._-]+$" id))
               (if (caddy-delete admin server id)
                   (reply 200 "application/json; charset=utf-8" "{\"status\":\"ok\"}")
                   (reply 502 "application/json; charset=utf-8" "{\"error\":\"caddy unavailable\"}"))
               (reply 400 "application/json; charset=utf-8" "{\"error\":\"invalid id\"}"))))))
    (define (allow-post)
      (reply 405 "text/plain" "method not allowed\n" (list (h 'allow "POST"))))
    (define (allow-delete)
      (reply 405 "text/plain" "method not allowed\n" (list (h 'allow "DELETE"))))
    (define (handler req body)
      (let* ((path (uri-path (request-uri req)))
             (method (request-method req))
             (bounded-body (read-body body)))
        (cond
         ((and (eq? method 'GET) (string=? path "/")) (main-response req))
         ((and (eq? method 'GET) (string=? path "/healthz"))
          (reply 200 "text/plain; charset=utf-8" "ok\n"))
         ((and (eq? method 'GET) (string=? path "/fragments/routes")) (routes-response))
         ((and (eq? method 'GET) (string=? path "/deadline/edit"))
          (let ((d (deadline-load state)))
             (render-deadline req (and (list? d) d) d #f #t #f)))
         ((and (eq? method 'GET)
               (or (member path static-paths) (member path font-paths)))
          (static-response static-dir path))
         ((and (member path '("/deadline" "/deadline/edit" "/deadline/reset" "/theme" "/api/routes"))
               (not (eq? method 'POST))) (allow-post))
         ((and (string-prefix? "/api/routes/" path) (not (eq? method 'DELETE)))
          (allow-delete))
         ((and (eq? method 'POST) (member path '("/deadline" "/deadline/edit")))
          (save-deadline req bounded-body))
         ((and (eq? method 'POST) (string=? path "/deadline/reset"))
          (reset-deadline req bounded-body))
         ((and (eq? method 'POST) (string=? path "/theme"))
          (save-theme req bounded-body))
         ((and (eq? method 'POST) (string=? path "/api/routes"))
          (api-upsert bounded-body))
          ((and (eq? method 'DELETE) (route-id path)) (api-delete path bounded-body))
         ((eq? method 'GET) (reply 404 "text/plain" "not found\n"))
         (else (reply 405 "text/plain" "method not allowed\n")))))
     ((module-ref (resolve-module '(web server)) 'run-server)
         handler bounded-http `(#:host ,bind #:port ,port #:max-body ,mutation-limit))))
